--- #These task installs and enables apache on webservers
- hosts: db
  become: yes
  vars:
   dbuser: ansible
   dbpassword: 12345
  tasks:
  - name: ensure mysql is installed
    apt: name={{ item }} state=present
    with_items:
      - mysql-server
      - libmysqlclient-dev
  - name: Install the Python MySQLB module
    pip: name=MySQL-python
  - name: ensure mysql is running
    service: name=mysql state=running enabled=yes
  - name: create application database
    mysql_db: name={{ item }} state=present
    with_items:
      - ansible_db01
      - ansible_db02
  - name: create application user
    mysql_user: name={{ dbuser }} password={{ dbpassword }} priv=*.*:ALL state=present
#
